Repository RedRoverSchool/JenkinsQA_2024_spring, pull requests merged in 2024-06, with the labels that each got.

#1637 [!] deleteNotes take nodes names from computer/ page
  src/test/java/school/redrover/runner/JenkinsUtils.java
Labels: RF

#1639 [!] assert is simplified
  src/test/java/school/redrover/NodesTest.java
Labels: RF

#1646 FreestyleProjectTest - Add Test Steps for Allure report
  src/test/java/school/redrover/FreestyleProjectTest.java
  src/test/java/school/redrover/model/ItemErrorPage.java
Labels: Allure

#1658 Add Allure steps to OrganizationFolderTest and FolderTest
  src/test/java/school/redrover/BuildHistoryTest.java
  src/test/java/school/redrover/FolderTest.java
  src/test/java/school/redrover/FreestyleProjectTest.java
  src/test/java/school/redrover/OrganizationFolderTest.java
  src/test/java/school/redrover/model/CreateNewItemPage.java
  src/test/java/school/redrover/model/DeleteDialog.java
  src/test/java/school/redrover/model/FolderProjectPage.java
  src/test/java/school/redrover/model/FolderRenamePage.java
  src/test/java/school/redrover/model/FreestyleProjectPage.java
  src/test/java/school/redrover/model/HomePage.java
  src/test/java/school/redrover/model/MovePage.java
  src/test/java/school/redrover/model/OrganizationFolderConfigPage.java
  src/test/java/school/redrover/model/OrganizationFolderProjectPage.java
  src/test/java/school/redrover/model/OrganizationFolderRenamePage.java
  src/test/java/school/redrover/model/PipelineSyntaxPage.java
Labels: RF

#1654 Create ui.bug-report.yml
  .github/ISSUE_TEMPLATE/ui.bug-report.yml
Labels: bug, documentation

#1666 Add Allure steps to MultibranchPipelineTest
  src/test/java/school/redrover/MultibranchPipelineTest.java
  src/test/java/school/redrover/model/CreateNewItemPage.java
  src/test/java/school/redrover/model/HomePage.java
  src/test/java/school/redrover/model/MultiConfigurationConfigPage.java
  src/test/java/school/redrover/model/MultibranchPipelineConfigPage.java
  src/test/java/school/redrover/model/MultibranchPipelineProjectPage.java
  src/test/java/school/redrover/model/MultibranchPipelineRenamePage.java
Labels: Allure

#1669 RF to POM: testAddDescriptionButtonBackgroundColor
  src/test/java/school/redrover/PipelineTest.java
  src/test/java/school/redrover/model/PipelineProjectPage.java
Labels: POM, RF

#1671 Add Step to everyone method which called from PipelineTest
  src/test/java/school/redrover/BuildHistoryTest.java
  src/test/java/school/redrover/FreestyleProjectTest.java
  src/test/java/school/redrover/PipelineTest.java
  src/test/java/school/redrover/model/BuildHistoryPage.java
  src/test/java/school/redrover/model/CreateItemErrorPage.java
  src/test/java/school/redrover/model/FreestyleRenamePage.java
  src/test/java/school/redrover/model/HeaderFrame.java
  src/test/java/school/redrover/model/HomePage.java
  src/test/java/school/redrover/model/NodeBuiltInStatusPage.java
  src/test/java/school/redrover/model/PipelineConfigPage.java
  src/test/java/school/redrover/model/PipelineProjectPage.java
  src/test/java/school/redrover/model/PipelineRenamePage.java
Labels: Allure
